name: flutter_ibadah
description: "A Flutter package for showing Bangladeshi salah time."
version: 0.0.5

environment:
  sdk: ^3.5.0
  flutter: ">=3.20.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/

  # To add custom fonts to your package, add a fonts section here,
  # in this format:
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/satoshi/Satoshi-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/satoshi/Satoshi-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Regular.ttf
          weight: 400

homepage: https://github.com/asfakur-rahat/flutter_ibadah
repository: https://github.com/asfakur-rahat/flutter_ibadah
license: MIT
